### ISSUE TITLE
Unable to play moves against opponent Marriage

### ISSUE THREAD

**Issue by JorrrK** [intelligent-systems-course/schnapsen#70]
Error:

Traceback (most recent call last):
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Joris\anaconda3\envs\intelligent_systems\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Joris\My Drive\AI Y1\Project Intelligent Systems\schnapsen-dev-main\src\schnapsen\bots\gui\guibot.py", line 103, in __sendmove
    return self.__generate(botname=botname)
  File "C:\Users\Joris\My Drive\AI Y1\Project Intelligent Systems\schnapsen-dev-main\src\schnapsen\bots\gui\guibot.py", line 112, in __generate
    json = _Old_GUI_Compatibility.player_game_state_to_json(state=state, leader_move=leader_move, game_over=state_exchange.is_game_over)
  File "C:\Users\Joris\My Drive\AI Y1\Project Intelligent Systems\schnapsen-dev-main\src\schnapsen\bots\gui\guibot.py", line 269, in player_game_state_to_json
    leadercard = previous_regular_trick.leader_move.as_regular_move().card
  File "C:\Users\Joris\My Drive\AI Y1\Project Intelligent Systems\schnapsen-dev-main\src\schnapsen\game.py", line 61, in as_regular_move
    raise AssertionError("as_regular_move called on a Move which is not a regular move. Check with is_regular_move first.")
AssertionError: as_regular_move called on a Move which is not a regular move. Check with is_regular_move first.

**Comment by miselico** [comment]
Thank you for reporting this.
